name: Capture Custom Figma Payload

on:
  repository_dispatch:
    types: [update-figma-variables]

jobs:
  capture_payload:
    name: Capture and Echo Payload
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event Type
        run: 'echo "Event Type: ${{ github.event.action }}"'
      
      - name: Echo Client Payload
        run: 'echo "Client Payload: ${{ toJson(github.event.client_payload) }}"'